name: "Publish NPM"
on: workflow_dispatch
jobs:
  publish-new-version:
    runs-on: ubuntu-latest
    name: Publish new version
    steps:
      - uses: actions/checkout@v3
        name: "Checkout code"
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        name: "Setup node"
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - run: sh scripts/deploy.sh
        name: "Publish to registry"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}